spring:
  config:
    import: classpath:env.properties
  application:
    name: echoVoice-user-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_id
            revision_type_field_name: revision_operation
            store_data_at_delete: true
            # track_entities_changed_in_revision: true
            # audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: classpath:/liquibase/db.changelog.xml
  mvc:
    servlet:
      path: "/${spring.application.name}"

server:
  port: 8080
  #servlet:
  #  context-path: "/${spring.application.name}"
