spring:
  config:
    import: classpath:env.properties
  application:
    name: evoice-authentication-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 5
  liquibase:
    change-log: classpath:/liquibase/db.changelog.xml
  mvc:
    servlet:
      path: "/${spring.application.name}"
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 50000

# EUREKA-SERVER (NAMING-SERVICE) PROPERTIES
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekauser:eureka!@localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8081
  #servlet:
  #  context-path: "/${spring.application.name}"
